name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Ensure gomobile deps
        run: |
          bash scripts/ensure_gomobile_deps.sh

      - name: Android SDK licenses
        run: yes | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Set up Flutter app
        run: |
          bash scripts/setup_flutter_app.sh

      - name: Build AAR and APK
        run: |
          bash scripts/build_android_manual.sh

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: lura-apk
          path: flutter_app/build/app/outputs/flutter-apk/*.apk

